(() => {
  const lang = new URLSearchParams(location.search).get('lang') || 'pl';
  const supported = ['pl', 'en', 'uk', 'ru'];
  const current = supported.includes(lang) ? lang : 'pl';
  const labels = { pl: 'PL', en: 'ENG', uk: 'UKR', ru: 'RU' };
  const copy = {
    en: {
      meta: ['Premises for a restaurant, café or bar | MazurEstate', 'We find and verify premises for restaurants, cafés and bars in Warsaw — before you sign a costly lease.'], nav: ['What we check', 'Examples', 'How we help', 'Reviews', 'FAQ', 'Let’s talk'],
      hero: ['PREMISES FOR HOSPITALITY', 'We’ll find a space where your concept can work', 'Restaurant, café or bar. Selection, technical verification and negotiation in one process.', 'Book a call', 'See how we help →'],
      intro: ['A BEAUTIFUL INTERIOR IS NOT ENOUGH', 'The premises must support your concept', 'We assess more than the address, frontage and rent. We check whether the back of house, installations, ventilation and logistics will allow you to open safely — without costly changes after signing.'],
      risksHead: ['LESS RISK. MORE CONTROL.', 'We check what cannot be seen from the dining room'], risks: [['Technical feasibility', 'Ventilation capacity and route, local extraction, electrical power, gas, refrigeration and connection points.'], ['Hygiene and function', 'Hot and cold water, drainage, washing area, toilets, storage and separation of clean and dirty flows.'], ['Total cost', 'Rent, fit-out, technical equipment, inspections and costs incurred before the first service.'], ['A safer agreement', 'Approvals for works, technical conditions, rent-free period, landlord contributions and a safe exit.']],
      casesHead: ['WHAT CAN HAPPEN WITHOUT VERIFICATION', 'The most expensive problems appear after signing', 'These are selected examples from the many risks involved in adapting hospitality premises. Every concept and building requires an individual review.'], labels: ['VENTILATION AND ACCESS', 'WATER AND DRAINAGE', 'REFRIGERATION AND NOISE'], titles: ['The unit is in the design — but cannot be brought inside', 'Water points exist, but not where the technology needs them', 'The cold room works, but heat and noise remain inside'], fields: ['Starting point', 'Problem', 'What caused it', 'How to avoid it'], cases: [['The designer selected a unit with the right capacity and identified its installation area.', 'The door, staircase or technical opening is too small, while roof delivery requires additional logistics and approvals.', 'The equipment was checked, but its delivery route, servicing access and future filter replacement were not.', 'Verify dimensions, transport route, service access and approvals before selecting the solution and premises.'], ['The property has water and drainage, so it appears to meet the basic requirements.', 'Once the kitchen is planned, connection points, falls or space for washing and additional hand basins are missing.', 'Installations were assessed without a kitchen technology plan, number of workstations and expected menu.', 'Compare the functional layout and equipment with the actual water and drainage routes before final negotiations.'], ['The required cold room fits and the electrical allocation appears sufficient.', 'There is no place or approval for an outdoor unit, while equipment releases heat and noise near residential neighbours.', 'The interior was checked, but not heat rejection, acoustics and rules for façades or common areas.', 'Agree equipment locations, acoustic parameters and heat rejection before signing.']],
      processHead: ['A SIMPLE PROCESS', 'From concept to the right premises'], process: [['We understand the concept', 'Menu, service model, number of covers, budget and opening date.'], ['We select premises', 'We show spaces that match the function and business model.'], ['We verify feasibility', 'We coordinate technical, sanitary, functional and formal checks.'], ['We negotiate the agreement', 'We secure fit-out time, necessary approvals and a clear division of responsibilities.']],
      expert: ['EXPERIENCE THAT PROTECTS YOUR BUDGET', 'Technology first. Agreement second.', 'We combine market knowledge with the work of the right designers and experts. You know early whether the premises can support your menu, equipment and service model.', ['a brief based on the real concept,', 'fewer unsuitable viewings,', 'verification of installations and logistics,', 'support during negotiations.'], 'Requirements depend on the type and scale of the business. Compliance is confirmed by the relevant specialists and authorities. ', 'View hygiene requirements'],
      reviewHead: ['CLIENT REVIEWS', 'Support that brings clarity to the decision', 'Draft copy — to be confirmed before publication.'], reviews: [['CAFÉ AND BAR', '“We assessed not only the guest area, but the entire back of house and installations. We knew which costs to include before negotiations.”', 'Julia K. · concept owner'], ['RESTAURANT', '“We received a shortlist of spaces that genuinely matched our kitchen technology and planned opening date.”', 'Michał P. · restaurateur'], ['BISTRO', '“The key was identifying constraints we had not noticed during the viewing. It changed how we negotiated with the owner.”', 'Anna and Paweł · co-owners'], ['PREMIUM RESTAURANT', '“The process was clear: concept, technical feasibility, costs and only then the agreement. The decision was based on facts.”', 'Tomasz R. · investor']],
      faqHead: ['FAQ', 'Frequently asked questions'], faq: [['Can every commercial unit become a restaurant?', 'No. Hospitality use depends on the property’s function, installations, ventilation, layout, the nature of the business and the approvals required.'], ['Does the property need separate ventilation?', 'The solution depends on the building and kitchen technology. We check extraction capacity, discharge route, supply air, servicing access and restrictions affecting common areas.'], ['Is running water in the property enough?', 'Not always. Hot and cold water, the number and location of points, drainage, falls and compatibility with the technology layout all matter.'], ['Do you check whether equipment can be installed?', 'Yes. We compare equipment requirements with power, installations, dimensions, delivery route, ventilation and future service access.'], ['Do you negotiate a rent-free period?', 'Yes. We help negotiate fit-out time, landlord contributions, approvals for works and clauses protecting the tenant.'], ['I have already selected premises. Can you check them?', 'Yes. We can begin with a specific property and coordinate the verification needed before your decision.'], ['How long does finding premises take?', 'It depends on the concept, budget, location and market availability. After the first call, we outline a realistic process and next steps.'], ['Are designers’ fees included?', 'We agree the scope individually. If an additional expert opinion is required, we confirm its cost and timing before commissioning it.']],
      cta: ['BEFORE YOU SIGN', 'Tell us about your concept', 'An initial call will help define the property brief, the main risks and the right next step.'], image: 'Illustrative image', carousel: ['Previous review', 'Next review'], subject: 'Premises for a hospitality business'
    },
    uk: {
      meta: ['Приміщення для ресторану, кафе або бару | MazurEstate', 'Знаходимо й перевіряємо приміщення для ресторанів, кафе та барів у Варшаві — до підписання дорогої оренди.'], nav: ['Що перевіряємо', 'Приклади', 'Як допомагаємо', 'Відгуки', 'FAQ', 'Поговорімо'],
      hero: ['ПРИМІЩЕННЯ ДЛЯ ГАСТРОНОМІЇ', 'Знайдемо простір, у якому Ваш концепт працюватиме', 'Ресторан, кафе або бар. Відбір, технічна перевірка й переговори в одному процесі.', 'Домовитися про дзвінок', 'Як ми допомагаємо →'], intro: ['ГАРНИЙ ІНТЕР’ЄР — ЦЕ НЕ ВСЕ', 'Приміщення має відповідати Вашому концепту', 'Оцінюємо не лише адресу, вітрину й оренду. Перевіряємо, чи дозволять технічні зони, комунікації, вентиляція й логістика безпечно відкритися — без дорогих змін після підписання.'],
      risksHead: ['МЕНШЕ РИЗИКУ. БІЛЬШЕ КОНТРОЛЮ.', 'Перевіряємо те, чого не видно із залу'], risks: [['Технічні можливості', 'Потужність і траса вентиляції, місцеві витяжки, електрика, газ, холодильне обладнання й точки підключення.'], ['Гігієна та функція', 'Гаряча й холодна вода, каналізація, мийна зона, санвузли, склади та розділення чистих і брудних потоків.'], ['Загальна вартість', 'Оренда, адаптація, технічне обладнання, приймання та витрати до першого сервісу.'], ['Безпечна угода', 'Погодження робіт, технічні умови, орендні канікули, участь власника у витратах і безпечний вихід.']],
      casesHead: ['ЩО МОЖЕ СТАТИСЯ БЕЗ ПЕРЕВІРКИ', 'Найдорожчі проблеми виникають після підписання', 'Це окремі приклади з багатьох ризиків адаптації гастрономічного приміщення. Кожен концепт і будівля потребують індивідуального аналізу.'], labels: ['ВЕНТИЛЯЦІЯ ТА ДОСТУП', 'ВОДА Й КАНАЛІЗАЦІЯ', 'ХОЛОД І ШУМ'], titles: ['Установка є в проєкті, але її неможливо занести', 'Точки води є, але не там, де їх потребує технологія', 'Холодильна камера працює, але тепло й шум залишаються всередині'], fields: ['Початкова ситуація', 'Проблема', 'Що до цього призвело', 'Як уникнути'], cases: [['Проєктувальник підібрав установку належної потужності й визначив місце монтажу.', 'Двері, сходи або технічний отвір замалі, а доставка через дах потребує додаткової логістики й погоджень.', 'Перевірили параметри обладнання, але не шлях доставки, сервісний доступ і майбутню заміну фільтрів.', 'Перевірити габарити, маршрут транспортування, сервісний доступ і погодження до вибору рішення та приміщення.'], ['У приміщенні є вода й каналізація, тож на перший погляд воно відповідає базовим вимогам.', 'Після планування кухні бракує потрібних підключень, ухилів або місця для мийної зони й додаткових умивальників.', 'Комунікації оцінили без технології кухні, кількості робочих місць і майбутнього меню.', 'Зіставити функціональне планування й обладнання з реальними трасами води та каналізації до фінальних переговорів.'], ['Потрібна холодильна камера поміщається, а виділена потужність здається достатньою.', 'Немає місця або дозволу на зовнішній блок, а обладнання віддає тепло й шум поруч із житлом.', 'Перевірили інтер’єр, але не відведення тепла, акустику й правила щодо фасаду та спільних частин.', 'Узгодити розміщення обладнання, акустичні параметри й відведення тепла до підписання угоди.']],
      processHead: ['ПРОСТИЙ ПРОЦЕС', 'Від концепту до правильного приміщення'], process: [['Розуміємо концепт', 'Меню, модель обслуговування, кількість місць, бюджет і дата відкриття.'], ['Добираємо приміщення', 'Показуємо простори, що відповідають функції та бізнес-моделі.'], ['Перевіряємо можливості', 'Координуємо технічний, санітарний, функціональний і формальний аналіз.'], ['Узгоджуємо договір', 'Дбаємо про час на адаптацію, потрібні дозволи й чіткий розподіл відповідальності.']],
      expert: ['ДОСВІД, ЩО ЗАХИЩАЄ БЮДЖЕТ', 'Спочатку технологія. Потім угода.', 'Поєднуємо знання ринку з роботою потрібних проєктувальників та експертів. Ви завчасно знаєте, чи відповідає приміщення меню, обладнанню й моделі обслуговування.', ['бриф на основі реального концепту,', 'менше невідповідних переглядів,', 'перевірка комунікацій і логістики,', 'підтримка в переговорах.'], 'Вимоги залежать від виду та масштабу діяльності. Відповідність підтверджують профільні фахівці й органи. ', 'Переглянути гігієнічні вимоги'],
      reviewHead: ['ВІДГУКИ КЛІЄНТІВ', 'Підтримка, що впорядковує рішення', 'Чернетки текстів — потребують підтвердження перед публікацією.'], reviews: [['КАФЕ Й БАР', '«Ми оцінили не лише зал, а й усе запліччя та комунікації. Ще до переговорів знали, які витрати врахувати».', 'Юлія К. · власниця концепту'], ['РЕСТОРАН', '«Ми отримали короткий список приміщень, які справді відповідали технології кухні та запланованій даті відкриття».', 'Міхал П. · ресторатор'], ['БІСТРО', '«Найважливішим було виявити обмеження, яких ми самі не побачили на перегляді. Це змінило розмову з власником».', 'Анна та Павел · співвласники'], ['ПРЕМІАЛЬНИЙ РЕСТОРАН', '«Процес був чітким: концепт, технічні можливості, витрати й лише потім угода. Рішення ґрунтувалося на фактах».', 'Томаш Р. · інвестор']],
      faqHead: ['FAQ', 'Найчастіші запитання'], faq: [['Чи кожне комерційне приміщення може стати рестораном?', 'Ні. Можливість ведення гастрономії залежить від функції, комунікацій, вентиляції, планування, характеру діяльності й потрібних дозволів.'], ['Чи потрібна окрема вентиляція?', 'Рішення залежить від будівлі й технології кухні. Перевіряємо потужність витяжки, трасу викиду, приплив, сервісний доступ та обмеження спільних частин.'], ['Чи достатньо, що є проточна вода?', 'Не завжди. Важливі гаряча й холодна вода, кількість і розташування точок, каналізація, ухили та відповідність технологічному плануванню.'], ['Чи перевіряєте можливість монтажу обладнання?', 'Так. Зіставляємо вимоги обладнання з потужністю, комунікаціями, габаритами, шляхом доставки, вентиляцією та сервісним доступом.'], ['Чи узгоджуєте орендні канікули?', 'Так. Допомагаємо узгодити час на адаптацію, участь власника у витратах, дозволи на роботи й умови захисту орендаря.'], ['Я вже обрав приміщення. Чи можете його перевірити?', 'Так. Можемо почати з конкретного об’єкта й скоординувати перевірку, потрібну перед рішенням.'], ['Скільки триває пошук?', 'Це залежить від концепту, бюджету, локації та ринкової пропозиції. Після першої розмови визначаємо реальний процес і наступні кроки.'], ['Чи входять послуги проєктувальників?', 'Обсяг визначаємо індивідуально. Якщо потрібна додаткова експертиза, її вартість і строки підтверджуємо до замовлення.']],
      cta: ['ДО ПІДПИСАННЯ УГОДИ', 'Розкажіть нам про свій концепт', 'Перша розмова допоможе визначити бриф приміщення, головні ризики й правильний наступний крок.'], image: 'Ілюстративне фото', carousel: ['Попередній відгук', 'Наступний відгук'], subject: 'Приміщення для гастрономії'
    },
    ru: {
      meta: ['Помещение для ресторана, кафе или бара | MazurEstate', 'Находим и проверяем помещения для ресторанов, кафе и баров в Варшаве — до подписания дорогостоящего договора аренды.'], nav: ['Что проверяем', 'Примеры', 'Как помогаем', 'Отзывы', 'FAQ', 'Поговорим'], hero: ['ПОМЕЩЕНИЯ ДЛЯ ГАСТРОНОМИИ', 'Найдём пространство, в котором ваш концепт будет работать', 'Ресторан, кафе или бар. Отбор, техническая проверка и переговоры в одном процессе.', 'Назначить звонок', 'Как мы помогаем →'], intro: ['КРАСИВОГО ИНТЕРЬЕРА НЕДОСТАТОЧНО', 'Помещение должно поддерживать ваш концепт', 'Оцениваем не только адрес, витрину и аренду. Проверяем, позволят ли технические зоны, коммуникации, вентиляция и логистика безопасно открыться — без дорогих изменений после подписания.'],
      risksHead: ['МЕНЬШЕ РИСКА. БОЛЬШЕ КОНТРОЛЯ.', 'Проверяем то, чего не видно из зала'], risks: [['Технические возможности', 'Мощность и трасса вентиляции, местные вытяжки, электрика, газ, холодильное оборудование и точки подключения.'], ['Гигиена и функция', 'Горячая и холодная вода, канализация, моечная, санузлы, склады и разделение чистых и грязных потоков.'], ['Общая стоимость', 'Аренда, адаптация, техническое оборудование, приёмка и расходы до первого сервиса.'], ['Безопасный договор', 'Согласования работ, технические условия, арендные каникулы, участие собственника в затратах и безопасный выход.']],
      casesHead: ['ЧТО МОЖЕТ ПРОИЗОЙТИ БЕЗ ПРОВЕРКИ', 'Самые дорогие проблемы возникают после подписания', 'Это лишь отдельные примеры из множества рисков адаптации гастрономического помещения. Каждый концепт и здание требуют индивидуального анализа.'], labels: ['ВЕНТИЛЯЦИЯ И ДОСТУП', 'ВОДА И КАНАЛИЗАЦИЯ', 'ХОЛОД И ШУМ'], titles: ['Установка есть в проекте, но её невозможно занести', 'Точки воды есть, но не там, где их требует технология', 'Холодильная камера работает, но тепло и шум остаются внутри'], fields: ['Исходная ситуация', 'Проблема', 'Что к этому привело', 'Как избежать'], cases: [['Проектировщик подобрал установку нужной мощности и определил место монтажа.', 'Дверь, лестница или технический проём слишком малы, а доставка через крышу требует дополнительной логистики и согласований.', 'Проверили параметры оборудования, но не путь доставки, сервисный доступ и будущую замену фильтров.', 'Проверить габариты, маршрут транспортировки, сервисный доступ и согласования до выбора решения и помещения.'], ['В помещении есть вода и канализация, поэтому на первый взгляд оно отвечает базовым требованиям.', 'После планирования кухни не хватает нужных подключений, уклонов или места для моечной и дополнительных умывальников.', 'Коммуникации оценили без технологии кухни, количества рабочих мест и будущего меню.', 'Сопоставить функциональную планировку и оборудование с реальными трассами воды и канализации до финальных переговоров.'], ['Нужная холодильная камера помещается, а выделенная мощность кажется достаточной.', 'Нет места или разрешения на наружный блок, а оборудование отдаёт тепло и шум рядом с жильём.', 'Проверили интерьер, но не отвод тепла, акустику и правила для фасада и общих частей.', 'Согласовать размещение оборудования, акустические параметры и отвод тепла до подписания договора.']],
      processHead: ['ПРОСТОЙ ПРОЦЕСС', 'От концепта до подходящего помещения'], process: [['Изучаем концепт', 'Меню, модель обслуживания, количество мест, бюджет и дата открытия.'], ['Подбираем помещения', 'Показываем пространства, соответствующие функции и бизнес-модели.'], ['Проверяем возможность реализации', 'Координируем технический, санитарный, функциональный и формальный анализ.'], ['Согласовываем договор', 'Добиваемся времени на адаптацию, необходимых разрешений и чёткого разделения ответственности.']],
      expert: ['ОПЫТ, КОТОРЫЙ ЗАЩИЩАЕТ БЮДЖЕТ', 'Сначала технология. Потом договор.', 'Объединяем знание рынка с работой нужных проектировщиков и экспертов. Вы заранее знаете, соответствует ли помещение меню, оборудованию и модели обслуживания.', ['бриф на основе реального концепта,', 'меньше неподходящих просмотров,', 'проверка коммуникаций и логистики,', 'поддержка в переговорах.'], 'Требования зависят от вида и масштаба деятельности. Соответствие подтверждают профильные специалисты и органы. ', 'Посмотреть гигиенические требования'],
      reviewHead: ['ОТЗЫВЫ КЛИЕНТОВ', 'Поддержка, которая упорядочивает решение', 'Черновые тексты — требуют подтверждения перед публикацией.'], reviews: [['КАФЕ И БАР', '«Мы оценили не только зал, но и всё подсобное пространство и коммуникации. Ещё до переговоров знали, какие расходы учесть».', 'Юлия К. · владелица концепта'], ['РЕСТОРАН', '«Мы получили короткий список помещений, которые действительно соответствовали технологии кухни и запланированной дате открытия».', 'Михал П. · ресторатор'], ['БИСТРО', '«Главным было выявить ограничения, которых мы сами не заметили на просмотре. Это изменило разговор с владельцем».', 'Анна и Павел · совладельцы'], ['ПРЕМИАЛЬНЫЙ РЕСТОРАН', '«Процесс был чётким: концепт, технические возможности, расходы и только потом договор. Решение основывалось на фактах».', 'Томаш Р. · инвестор']],
      faqHead: ['FAQ', 'Частые вопросы'], faq: [['Каждое ли коммерческое помещение может стать рестораном?', 'Нет. Возможность вести гастрономию зависит от функции, коммуникаций, вентиляции, планировки, характера деятельности и необходимых согласований.'], ['Нужна ли отдельная вентиляция?', 'Решение зависит от здания и технологии кухни. Проверяем мощность вытяжки, трассу выброса, приток, сервисный доступ и ограничения общих частей.'], ['Достаточно ли наличия проточной воды?', 'Не всегда. Важны горячая и холодная вода, количество и расположение точек, канализация, уклоны и соответствие технологической планировке.'], ['Проверяете ли вы возможность монтажа оборудования?', 'Да. Сопоставляем требования оборудования с мощностью, коммуникациями, габаритами, путём доставки, вентиляцией и сервисным доступом.'], ['Вы согласовываете арендные каникулы?', 'Да. Помогаем согласовать время на адаптацию, участие собственника в затратах, разрешения на работы и условия защиты арендатора.'], ['Я уже выбрал помещение. Можете его проверить?', 'Да. Можем начать с конкретного объекта и скоординировать проверку, необходимую до решения.'], ['Сколько длится поиск?', 'Это зависит от концепта, бюджета, локации и рыночного предложения. После первой беседы определяем реалистичный процесс и следующие шаги.'], ['Включены ли услуги проектировщиков?', 'Объём определяем индивидуально. Если нужна дополнительная экспертиза, её стоимость и сроки подтверждаем до заказа.']],
      cta: ['ДО ПОДПИСАНИЯ ДОГОВОРА', 'Расскажите нам о своём концепте', 'Первая беседа поможет определить бриф помещения, основные риски и правильный следующий шаг.'], image: 'Иллюстративное фото', carousel: ['Предыдущий отзыв', 'Следующий отзыв'], subject: 'Помещение для гастрономии'
    }
  };
  const q = s => document.querySelector(s), qa = s => [...document.querySelectorAll(s)], set = (s, v) => { const e = q(s); if (e) e.textContent = v; };
  document.documentElement.lang = current;
  if (current === 'pl') return; const d = copy[current]; document.title = d.meta[0]; q('meta[name="description"]').content = d.meta[1];
  ['.medical-hero .eyebrow','.medical-hero h1','.medical-hero .hero-copy>p:not(.eyebrow)','.medical-hero .button','.medical-hero .hero-actions>a:last-child'].forEach((s,i)=>set(s,d.hero[i]));
  ['.intro .eyebrow','.intro h2','.intro>div:last-child p'].forEach((s,i)=>set(s,d.intro[i])); ['.risk-section .eyebrow','.risk-section h2'].forEach((s,i)=>set(s,d.risksHead[i]));
  qa('.risk-grid article').forEach((e,i)=>{e.querySelector('h3').textContent=d.risks[i][0];e.querySelector('p').textContent=d.risks[i][1]});
  const head=q('.case-section>.section-head');[head.querySelector('.eyebrow'),head.querySelector('h2'),head.querySelector('p:last-child')].forEach((e,i)=>e.textContent=d.casesHead[i]);
  qa('.case-grid article').forEach((e,i)=>{e.querySelector('.case-tag').dataset.label=d.labels[i];e.querySelector('h3').textContent=d.titles[i];[...e.querySelectorAll('.case-details>div')].forEach((r,j)=>{r.querySelector('b').textContent=d.fields[j];r.querySelector('p').textContent=d.cases[i][j]})});
  ['.process-section .eyebrow','.process-section h2'].forEach((s,i)=>set(s,d.processHead[i]));qa('.process-grid article').forEach((e,i)=>{e.querySelector('h3').textContent=d.process[i][0];e.querySelector('p').textContent=d.process[i][1]});
  const ex=q('.checks'),link=q('.legal-note a');ex.querySelector('.eyebrow').textContent=d.expert[0];ex.querySelector('h2').textContent=d.expert[1];ex.querySelector(':scope>div:last-child>p:not(.eyebrow):not(.legal-note)').textContent=d.expert[2];qa('.checks li').forEach((e,i)=>e.textContent=d.expert[3][i]);q('.legal-note').replaceChildren(document.createTextNode(d.expert[4]),link);link.textContent=d.expert[5];set('.checks-image span',d.image);
  ['.testimonials .eyebrow','.testimonials h2','.testimonials .draft-note'].forEach((s,i)=>set(s,d.reviewHead[i]));qa('.testimonial-track article').forEach((e,i)=>{e.querySelector('span').textContent=d.reviews[i][0];e.querySelector('blockquote').textContent=d.reviews[i][1];e.querySelector('p').textContent=d.reviews[i][2]});qa('.carousel-controls button').forEach((e,i)=>e.setAttribute('aria-label',d.carousel[i]));
  ['.faq .eyebrow','.faq h2'].forEach((s,i)=>set(s,d.faqHead[i]));qa('.faq details').forEach((e,i)=>{e.querySelector('summary').textContent=d.faq[i][0];e.querySelector('p').textContent=d.faq[i][1]});
  ['.final-cta .eyebrow','.final-cta h2','.final-cta>div:first-child>p:last-child'].forEach((s,i)=>set(s,d.cta[i]));q('.final-cta a[href^="mailto:"]').href=`mailto:info@mazurestate.com?subject=${encodeURIComponent(d.subject)}`;
})();
