(() => {
  const params = new URLSearchParams(location.search);
  const lang = ['pl', 'en', 'uk', 'ru'].includes(params.get('lang')) ? params.get('lang') : 'pl';
  const labels = { pl: 'PL', en: 'ENG', uk: 'UKR', ru: 'RU' };
  const copy = {
    en: {
      meta: ['Premises for a medical or dental practice | MazurEstate', 'We find and verify premises for medical, dental and aesthetic medicine practices in Warsaw — before you sign a costly lease.'],
      nav: ['What we check', 'Examples', 'How we help', 'Reviews', 'FAQ', 'Let’s talk'],
      hero: ['PREMISES FOR MEDICAL BUSINESSES', 'We’ll find a space ready for your practice', 'Dentistry, medical practice or aesthetic medicine. Selection, verification and negotiation in one process.', 'Book a call', 'See how we help →'],
      intro: ['A GOOD ADDRESS IS ONLY THE BEGINNING', 'The space must fit your practice', 'We assess more than location and price. We check whether a property has the technical and functional potential you need, then help negotiate safer terms.'],
      risksHead: ['LESS RISK. MORE CERTAINTY.', 'We check what a viewing does not reveal'],
      risks: [['Technical feasibility', 'We verify hidden constraints: ventilation, water and drainage risers, electrical capacity, other installations and equipment requirements. This is where experience helps prevent the costliest surprises.'], ['Formal conditions', 'Documents, required approvals and restrictions affecting the planned works.'], ['Total cost', 'Rent, fit-out, schedule and costs incurred before opening.'], ['A safer agreement', 'Rent-free periods, fit-out expenses, approvals and clauses that protect the tenant.']],
      casesHead: ['WHAT CAN HAPPEN WITHOUT VERIFICATION', 'Problems begin after the agreement is signed', 'These are only three examples of the many risks that may arise when adapting premises. Check them early — before rent starts running and the opening deadline approaches.'],
      caseLabels: ['TECHNICAL INSTALLATIONS', 'LAYOUT AND ACCESSIBILITY', 'DENTAL INSTALLATIONS'],
      caseTitles: ['There is no route for the installation', 'The functional layout no longer fits', 'A dental unit needs more than free space'],
      caseFields: ['Starting point', 'Problem', 'What caused it', 'How to avoid it'],
      cases: [
        ['A new, attractive space and an agreed long-term lease.', 'The design requires additional ventilation, but the route crosses the façade, roof or common area.', 'Installation options and the building manager’s position were checked only after choosing the premises.', 'Verify the documentation, installation route and required approvals before signing.'],
        ['The floor area looks sufficient and the property seems easy to adapt.', 'The accessible restroom, required circulation and treatment rooms require walls and installations to be moved.', 'The functional programme was prepared only after the agreement was signed.', 'Prepare an initial layout with a designer and reject the premises if no safe solution is possible.'],
        ['The plan has room for a unit and an ergonomic treatment room.', 'Water, drainage, power and equipment connections are too far away or difficult to install.', 'Equipment requirements and back-of-house organisation were defined too late.', 'Compare equipment and service requirements with the property’s installations before final terms are negotiated.']
      ],
      processHead: ['A SIMPLE PROCESS', 'From an idea to the right premises'],
      process: [['We define your needs', 'Type of practice, location, budget and opening date.'], ['We select premises', 'We show only spaces that match the agreed brief.'], ['We verify risks', 'We coordinate technical, functional and formal checks.'], ['We negotiate the agreement', 'We secure terms that support a safe fit-out process.']],
      expertise: ['EXPERIENCE THAT PROTECTS YOUR BUDGET', 'You are not making the decision alone', 'We combine market knowledge with coordination of the right experts. You learn about a property’s limitations early and can compare options with confidence.', ['clear selection criteria,', 'fewer unsuitable viewings,', 'verification before signing,', 'support during negotiations.'], 'Requirements depend on the planned services. Compliance must be confirmed by the relevant qualified specialists and authorities. ', 'View the legal basis'],
      testimonialsHead: ['CLIENT REVIEWS', 'Support that makes a good start easier', 'Draft copy — to be confirmed before publication.'],
      testimonials: [['DENTISTRY', '“We received a shortlist of spaces that genuinely suited our model. We understood the key technical risks before signing the agreement.”', 'Anna K. · practice owner'], ['SPECIALIST CLINIC', '“MazurEstate organised the entire process, from requirements to negotiations. We knew what to ask and which clauses mattered most.”', 'Marek S. · clinic co-owner'], ['AESTHETIC MEDICINE', '“I wanted a representative address without functional compromises. The selected premises met both goals and stayed within budget.”', 'Karolina M. · aesthetic medicine doctor'], ['PHYSIOTHERAPY', '“We did not waste time on random listings. Every space we viewed matched our criteria and growth plan.”', 'Piotr W. · physiotherapist'], ['MEDICAL PRACTICE', '“The greatest value was making a calm, fact-based decision. We had support with the property review and owner negotiations.”', 'Joanna L. · practice owner']],
      faqHead: ['FAQ', 'Frequently asked questions'],
      faq: [['Is every commercial unit suitable for a medical practice?', 'No. It depends on the services, the property’s parameters and installations, and the approvals required. That is why we verify the space before the agreement is signed.'], ['Do you help with technical verification?', 'Yes. We coordinate the review and, when needed, cooperation with the appropriate designers and specialists.'], ['Do you negotiate lease terms?', 'Yes. We analyse rent, rent-free periods, fit-out expenses, approvals for works and protections related to adaptation.'], ['When is the best time to contact you?', 'Ideally before beginning the search or before signing an agreement for a selected property.'], ['I have already selected a property. Can you check it?', 'Yes. We can begin with a review of that property, prepare questions for the owner and coordinate the verification needed before your decision.'], ['Do you assist with both leases and purchases?', 'Yes. We tailor the scope of analysis and negotiation to the transaction and the planned use.'], ['How long does finding and checking premises take?', 'It depends on the brief, market availability and the consultations required. We agree the stages and a realistic schedule at the start.'], ['Are designers and expert reports included?', 'We agree the scope individually. If a designer or specialist opinion is needed, we confirm its cost and timing before commissioning it.']],
      cta: ['BEFORE YOU SIGN', 'Tell us what kind of practice you are planning', 'An initial call will help define the property brief, the main risks and the right next step.'],
      imageBadge: 'Illustrative image',
      carousel: ['Previous review', 'Next review'],
      mailSubject: 'Premises for a medical practice'
    },
    uk: {
      meta: ['Приміщення для медичного або стоматологічного кабінету | MazurEstate', 'Знаходимо й перевіряємо приміщення для медичних, стоматологічних кабінетів і естетичної медицини у Варшаві — до підписання дорогої угоди.'],
      nav: ['Що перевіряємо', 'Приклади', 'Як допомагаємо', 'Відгуки', 'FAQ', 'Поговорімо'],
      hero: ['ПРИМІЩЕННЯ ДЛЯ МЕДИЧНОГО БІЗНЕСУ', 'Знайдемо приміщення, готове до Вашої практики', 'Стоматологія, медичний кабінет або естетична медицина. Відбір, перевірка й переговори в одному процесі.', 'Домовитися про дзвінок', 'Як ми допомагаємо →'],
      intro: ['ВДАЛА АДРЕСА — ЛИШЕ ПОЧАТОК', 'Приміщення має відповідати Вашій діяльності', 'Ми оцінюємо не лише локацію та ціну. Перевіряємо технічний і функціональний потенціал простору, а потім допомагаємо узгодити безпечні умови.'],
      risksHead: ['МЕНШЕ РИЗИКУ. БІЛЬШЕ ВПЕВНЕНОСТІ.', 'Перевіряємо те, чого не видно під час огляду'],
      risks: [['Технічні можливості', 'Перевіряємо приховані обмеження: вентиляцію, водопровідні та каналізаційні стояки, електричну потужність, комунікації й можливість монтажу обладнання. Саме тут досвід допомагає уникнути найдорожчих сюрпризів.'], ['Формальні умови', 'Документи, необхідні погодження й обмеження запланованих робіт.'], ['Загальна вартість', 'Оренда, адаптація, графік і витрати до відкриття.'], ['Безпечна угода', 'Орендні канікули, витрати, погодження й умови, що захищають орендаря.']],
      casesHead: ['ЩО МОЖЕ СТАТИСЯ БЕЗ ПЕРЕВІРКИ', 'Проблеми починаються після підписання угоди', 'Це лише три приклади з багатьох ризиків, які можуть виникнути під час адаптації приміщення. Варто перевірити їх заздалегідь — до початку нарахування оренди та наближення дати відкриття.'],
      caseLabels: ['ТЕХНІЧНІ КОМУНІКАЦІЇ', 'ПЛАНУВАННЯ Й ДОСТУПНІСТЬ', 'СТОМАТОЛОГІЧНІ КОМУНІКАЦІЇ'],
      caseTitles: ['Немає шляху для прокладання комунікацій', 'Функціональне планування не поміщається', 'Стоматологічній установці потрібно більше, ніж вільне місце'],
      caseFields: ['Початкова ситуація', 'Проблема', 'Що до цього призвело', 'Як уникнути'],
      cases: [['Нове привабливе приміщення й погоджена довгострокова оренда.', 'Проєкт потребує додаткової вентиляції, але траса проходить через фасад, дах або спільну частину.', 'Можливості комунікацій і позицію управителя перевірили лише після вибору приміщення.', 'Перевірити документацію, трасу комунікацій і потрібні погодження до підписання угоди.'], ['Площа здається достатньою, а приміщення — простим для адаптації.', 'Доступний санвузол, необхідні проходи й кабінети потребують перенесення стін і комунікацій.', 'Функціональну програму створили лише після підписання угоди.', 'Підготувати попереднє планування з проєктувальником і відмовитися від приміщення, якщо безпечного рішення немає.'], ['У плані є місце для установки та ергономічного кабінету.', 'Вода, каналізація, живлення й підключення обладнання розташовані надто далеко або їх складно виконати.', 'Вимоги обладнання й організацію допоміжних зон визначили надто пізно.', 'Зіставити вимоги обладнання та послуг із комунікаціями приміщення до фінальних переговорів.']],
      processHead: ['ПРОСТИЙ ПРОЦЕС', 'Від ідеї до правильного приміщення'],
      process: [['Визначаємо потреби', 'Профіль діяльності, локація, бюджет і дата відкриття.'], ['Добираємо приміщення', 'Показуємо лише простори, що відповідають погодженому брифу.'], ['Перевіряємо ризики', 'Координуємо технічний, функціональний і формальний аналіз.'], ['Узгоджуємо договір', 'Дбаємо про умови для безпечної підготовки приміщення.']],
      expertise: ['ДОСВІД, ЩО ЗАХИЩАЄ БЮДЖЕТ', 'Ви не залишаєтесь із рішенням наодинці', 'Поєднуємо знання ринку з координацією потрібних експертів. Ви завчасно дізнаєтесь про обмеження приміщення й можете впевнено порівняти варіанти.', ['чіткі критерії вибору,', 'менше невідповідних переглядів,', 'перевірка до підписання угоди,', 'підтримка в переговорах.'], 'Вимоги залежать від запланованих послуг. Відповідність проєкту підтверджують профільні фахівці та органи. ', 'Переглянути правову основу'],
      testimonialsHead: ['ВІДГУКИ КЛІЄНТІВ', 'Підтримка, що полегшує вдалий старт', 'Чернетки текстів — потребують підтвердження перед публікацією.'],
      testimonials: [['СТОМАТОЛОГІЯ', '«Ми отримали короткий список приміщень, які справді відповідали нашій моделі. Ключові технічні ризики були відомі до підписання угоди».', 'Анна К. · власниця кабінету'], ['СПЕЦІАЛІЗОВАНА КЛІНІКА', '«MazurEstate упорядкувало весь процес — від вимог до переговорів. Ми знали, про що запитувати і які положення угоди були ключовими».', 'Марек С. · співвласник клініки'], ['ЕСТЕТИЧНА МЕДИЦИНА', '«Для мене були важливі представницьке місце й функціональність. Обране приміщення виконало обидва завдання та вклалося в бюджет».', 'Кароліна М. · лікарка естетичної медицини'], ['ФІЗІОТЕРАПІЯ', '«Ми не витрачали час на випадкові пропозиції. Кожен показаний простір відповідав нашим критеріям і плану розвитку».', 'Пьотр В. · фізіотерапевт'], ['МЕДИЧНИЙ КАБІНЕТ', '«Найціннішим було спокійне рішення на основі фактів. Ми отримали підтримку під час перевірки приміщення й переговорів із власником».', 'Йоанна Л. · власниця практики']],
      faqHead: ['FAQ', 'Найчастіші запитання'],
      faq: [['Чи кожне комерційне приміщення підходить для кабінету?', 'Ні. Це залежить від виду послуг, параметрів приміщення, комунікацій і необхідних погоджень. Саме тому ми перевіряємо простір до підписання угоди.'], ['Чи допомагаєте з технічною перевіркою?', 'Так. Ми координуємо аналіз і, за потреби, співпрацю з відповідними проєктувальниками та фахівцями.'], ['Чи ведете переговори щодо умов оренди?', 'Так. Аналізуємо орендну плату, орендні канікули, витрати, погодження робіт і захисні умови, пов’язані з адаптацією.'], ['Коли найкраще звернутися?', 'Найкраще — до початку пошуку або до підписання угоди на обране приміщення.'], ['Я вже обрав приміщення. Чи можете його перевірити?', 'Так. Можемо почати з оцінки конкретного об’єкта, підготувати запитання власнику й скоординувати потрібну перевірку.'], ['Чи допомагаєте і з орендою, і з купівлею?', 'Так. Обсяг аналізу й переговорів адаптуємо до виду угоди та запланованої діяльності.'], ['Скільки триває пошук і перевірка?', 'Це залежить від брифу, доступності пропозицій і необхідних консультацій. На початку погоджуємо етапи та реалістичний графік.'], ['Чи входять послуги проєктувальників та експертизи?', 'Обсяг співпраці визначаємо індивідуально. Якщо потрібен висновок фахівця, його вартість і строки підтверджуємо до замовлення.']],
      cta: ['ДО ПІДПИСАННЯ УГОДИ', 'Розкажіть, який кабінет Ви плануєте', 'Перша розмова допоможе визначити бриф приміщення, головні ризики й правильний наступний крок.'], imageBadge: 'Ілюстративне фото', carousel: ['Попередній відгук', 'Наступний відгук'], mailSubject: 'Приміщення для медичної діяльності'
    },
    ru: {
      meta: ['Помещение для медицинского или стоматологического кабинета | MazurEstate', 'Находим и проверяем помещения для медицинских, стоматологических кабинетов и эстетической медицины в Варшаве — до подписания дорогостоящего договора.'],
      nav: ['Что проверяем', 'Примеры', 'Как помогаем', 'Отзывы', 'FAQ', 'Поговорим'],
      hero: ['ПОМЕЩЕНИЯ ДЛЯ МЕДИЦИНСКОГО БИЗНЕСА', 'Найдём помещение, готовое для вашей практики', 'Стоматология, медицинский кабинет или эстетическая медицина. Отбор, проверка и переговоры в одном процессе.', 'Назначить звонок', 'Как мы помогаем →'],
      intro: ['УДАЧНЫЙ АДРЕС — ТОЛЬКО НАЧАЛО', 'Помещение должно соответствовать вашей деятельности', 'Мы оцениваем не только локацию и цену. Проверяем технический и функциональный потенциал пространства, а затем помогаем согласовать безопасные условия.'],
      risksHead: ['МЕНЬШЕ РИСКА. БОЛЬШЕ УВЕРЕННОСТИ.', 'Проверяем то, чего не видно на просмотре'],
      risks: [['Технические возможности', 'Проверяем скрытые ограничения: вентиляцию, водопроводные и канализационные стояки, электрическую мощность, коммуникации и возможность монтажа оборудования. Именно здесь опыт помогает избежать самых дорогих сюрпризов.'], ['Формальные условия', 'Документы, необходимые согласования и ограничения планируемых работ.'], ['Общая стоимость', 'Аренда, адаптация, график и расходы до открытия.'], ['Безопасный договор', 'Арендные каникулы, затраты, согласования и условия, защищающие арендатора.']],
      casesHead: ['ЧТО МОЖЕТ ПРОИЗОЙТИ БЕЗ ПРОВЕРКИ', 'Проблемы начинаются после подписания договора', 'Это лишь три примера из множества рисков при адаптации помещения. Их стоит проверить заранее — до начала начисления аренды и приближения даты открытия.'],
      caseLabels: ['ТЕХНИЧЕСКИЕ КОММУНИКАЦИИ', 'ПЛАНИРОВКА И ДОСТУПНОСТЬ', 'СТОМАТОЛОГИЧЕСКИЕ КОММУНИКАЦИИ'], caseTitles: ['Нет пути для прокладки коммуникаций', 'Функциональная планировка не помещается', 'Стоматологической установке нужно больше, чем свободное место'], caseFields: ['Исходная ситуация', 'Проблема', 'Что к этому привело', 'Как избежать'],
      cases: [['Новое привлекательное помещение и согласованная долгосрочная аренда.', 'Проект требует дополнительной вентиляции, но трасса проходит через фасад, крышу или общую часть.', 'Возможности коммуникаций и позицию управляющего проверили только после выбора помещения.', 'Проверить документацию, трассу коммуникаций и необходимые согласования до подписания договора.'], ['Площадь кажется достаточной, а помещение — простым для адаптации.', 'Доступный санузел, необходимые проходы и кабинеты требуют переноса стен и коммуникаций.', 'Функциональную программу подготовили только после подписания договора.', 'Подготовить предварительную планировку с проектировщиком и отказаться от помещения, если безопасного решения нет.'], ['В плане есть место для установки и эргономичного кабинета.', 'Вода, канализация, питание и подключения оборудования находятся слишком далеко или сложны в реализации.', 'Требования оборудования и организацию вспомогательных зон определили слишком поздно.', 'Сопоставить требования оборудования и услуг с коммуникациями помещения до финальных переговоров.']],
      processHead: ['ПРОСТОЙ ПРОЦЕСС', 'От идеи до подходящего помещения'], process: [['Определяем потребности', 'Профиль деятельности, локация, бюджет и дата открытия.'], ['Подбираем помещения', 'Показываем только пространства, соответствующие согласованному брифу.'], ['Проверяем риски', 'Координируем технический, функциональный и формальный анализ.'], ['Согласовываем договор', 'Добиваемся условий для безопасной подготовки помещения.']],
      expertise: ['ОПЫТ, КОТОРЫЙ ЗАЩИЩАЕТ БЮДЖЕТ', 'Вы не остаётесь с решением один на один', 'Объединяем знание рынка с координацией нужных экспертов. Вы заранее узнаёте об ограничениях помещения и можете уверенно сравнивать варианты.', ['чёткие критерии выбора,', 'меньше неподходящих просмотров,', 'проверка до подписания договора,', 'поддержка в переговорах.'], 'Требования зависят от планируемых услуг. Соответствие проекта подтверждают профильные специалисты и органы. ', 'Посмотреть правовую основу'],
      testimonialsHead: ['ОТЗЫВЫ КЛИЕНТОВ', 'Поддержка, которая облегчает удачный старт', 'Черновые тексты — требуют подтверждения перед публикацией.'], testimonials: [['СТОМАТОЛОГИЯ', '«Мы получили короткий список помещений, которые действительно подходили нашей модели. Ключевые технические риски были известны до подписания договора».', 'Анна К. · владелица кабинета'], ['СПЕЦИАЛИЗИРОВАННАЯ КЛИНИКА', '«MazurEstate организовало весь процесс — от требований до переговоров. Мы знали, о чём спрашивать и какие пункты договора были ключевыми».', 'Марек С. · совладелец клиники'], ['ЭСТЕТИЧЕСКАЯ МЕДИЦИНА', '«Мне были важны представительное место и функциональность. Выбранное помещение решило обе задачи и уложилось в бюджет».', 'Каролина М. · врач эстетической медицины'], ['ФИЗИОТЕРАПИЯ', '«Мы не тратили время на случайные предложения. Каждое показанное пространство соответствовало критериям и плану развития».', 'Пётр В. · физиотерапевт'], ['МЕДИЦИНСКИЙ КАБИНЕТ', '«Главной ценностью было спокойное решение на основе фактов. Мы получили поддержку при проверке помещения и переговорах с владельцем».', 'Йоанна Л. · владелица практики']],
      faqHead: ['FAQ', 'Частые вопросы'], faq: [['Каждое ли коммерческое помещение подходит для кабинета?', 'Нет. Это зависит от вида услуг, параметров помещения, коммуникаций и необходимых согласований. Поэтому мы проверяем пространство до подписания договора.'], ['Помогаете ли вы с технической проверкой?', 'Да. Мы координируем анализ и при необходимости работу с профильными проектировщиками и специалистами.'], ['Вы ведёте переговоры по условиям аренды?', 'Да. Анализируем арендную плату, арендные каникулы, затраты, согласования работ и защитные условия, связанные с адаптацией.'], ['Когда лучше всего обратиться?', 'Лучше всего — до начала поиска или до подписания договора на выбранное помещение.'], ['Я уже выбрал помещение. Можете его проверить?', 'Да. Можем начать с оценки конкретного объекта, подготовить вопросы владельцу и скоординировать необходимую проверку.'], ['Помогаете и с арендой, и с покупкой?', 'Да. Объём анализа и переговоров адаптируем к виду сделки и планируемой деятельности.'], ['Сколько длится поиск и проверка?', 'Это зависит от брифа, доступности предложений и необходимых консультаций. В начале мы согласуем этапы и реалистичный график.'], ['Включены ли услуги проектировщиков и экспертизы?', 'Объём сотрудничества определяем индивидуально. Если нужно заключение специалиста, его стоимость и сроки подтверждаем до заказа.']],
      cta: ['ДО ПОДПИСАНИЯ ДОГОВОРА', 'Расскажите, какой кабинет вы планируете', 'Первая беседа поможет определить бриф помещения, основные риски и правильный следующий шаг.'], imageBadge: 'Иллюстративное фото', carousel: ['Предыдущий отзыв', 'Следующий отзыв'], mailSubject: 'Помещение для медицинской деятельности'
    }
  };

  document.documentElement.lang = lang;
  document.querySelector('.medical-language > button span').textContent = labels[lang];
  document.querySelector('.medical-brand').href = `../index.html?lang=${lang}`;
  document.querySelectorAll('.medical-language > div a').forEach(link => {
    const target = new URL(link.href).searchParams.get('lang');
    link.setAttribute('aria-current', target === lang ? 'page' : 'false');
  });
  if (lang === 'pl') return;
  const d = copy[lang];
  const q = selector => document.querySelector(selector);
  const qa = selector => [...document.querySelectorAll(selector)];
  const set = (selector, value) => { const element = q(selector); if (element) element.textContent = value; };
  document.title = d.meta[0];
  q('meta[name="description"]')?.setAttribute('content', d.meta[1]);
  qa('.medical-nav a').forEach((element, index) => element.textContent = d.nav[index]);
  q('.medical-header-actions > .button').textContent = d.nav[5];
  q('.medical-phone').setAttribute('aria-label', `${d.nav[5]}: +48 503 937 749`);
  ['.medical-hero .eyebrow', '.medical-hero h1', '.medical-hero .hero-copy > p:not(.eyebrow)', '.medical-hero .button', '.medical-hero .hero-actions > a:last-child'].forEach((selector, index) => set(selector, d.hero[index]));
  ['.intro .eyebrow', '.intro h2', '.intro > div:last-child p'].forEach((selector, index) => set(selector, d.intro[index]));
  ['.risk-section .section-head .eyebrow', '.risk-section .section-head h2'].forEach((selector, index) => set(selector, d.risksHead[index]));
  qa('.risk-grid article').forEach((card, index) => { card.querySelector('h3').textContent = d.risks[index][0]; card.querySelector('p').textContent = d.risks[index][1]; });
  const caseHead = q('.case-section > .section-head');
  [caseHead.querySelector('.eyebrow'), caseHead.querySelector('h2'), caseHead.querySelector('p:last-child')].forEach((element, index) => element.textContent = d.casesHead[index]);
  qa('.case-grid article').forEach((card, index) => {
    card.querySelector('.case-tag').dataset.label = d.caseLabels[index];
    card.querySelector('h3').textContent = d.caseTitles[index];
    [...card.querySelectorAll('.case-details > div')].forEach((row, rowIndex) => { row.querySelector('b').textContent = d.caseFields[rowIndex]; row.querySelector('p').textContent = d.cases[index][rowIndex]; });
  });
  ['.process-section .eyebrow', '.process-section h2'].forEach((selector, index) => set(selector, d.processHead[index]));
  qa('.process-grid article').forEach((card, index) => { card.querySelector('h3').textContent = d.process[index][0]; card.querySelector('p').textContent = d.process[index][1]; });
  const checks = q('.checks');
  checks.querySelector('.eyebrow').textContent = d.expertise[0]; checks.querySelector('h2').textContent = d.expertise[1]; checks.querySelector(':scope > div:last-child > p:not(.eyebrow):not(.legal-note)').textContent = d.expertise[2];
  qa('.checks li').forEach((element, index) => element.textContent = d.expertise[3][index]);
  const legalLink = q('.legal-note a'); q('.legal-note').replaceChildren(document.createTextNode(d.expertise[4]), legalLink); legalLink.textContent = d.expertise[5];
  q('.checks-image span').textContent = d.imageBadge;
  ['.testimonials .eyebrow', '.testimonials h2', '.testimonials .draft-note'].forEach((selector, index) => set(selector, d.testimonialsHead[index]));
  qa('.testimonial-track article').forEach((card, index) => { card.querySelector('span').textContent = d.testimonials[index][0]; card.querySelector('blockquote').textContent = d.testimonials[index][1]; card.querySelector('p').textContent = d.testimonials[index][2]; });
  qa('.carousel-controls button').forEach((button, index) => button.setAttribute('aria-label', d.carousel[index]));
  ['.faq .eyebrow', '.faq h2'].forEach((selector, index) => set(selector, d.faqHead[index]));
  qa('.faq details').forEach((item, index) => { item.querySelector('summary').textContent = d.faq[index][0]; item.querySelector('p').textContent = d.faq[index][1]; });
  ['.final-cta .eyebrow', '.final-cta h2', '.final-cta > div:first-child > p:last-child'].forEach((selector, index) => set(selector, d.cta[index]));
  q('.final-cta a[href^="mailto:"]').href = `mailto:info@mazurestate.com?subject=${encodeURIComponent(d.mailSubject)}`;
})();
