(() => {
  const params = new URLSearchParams(location.search);
  const type = ['mieszkania','domy','dzialki','lokale'].includes(params.get('type')) ? params.get('type') : 'mieszkania';
  const transaction = params.get('transaction') === 'wynajem' ? 'wynajem' : 'sprzedaz';
  const locationFilter = params.get('location') || '';
  const lang = ['pl','uk','en','ru'].includes(params.get('lang')) ? params.get('lang') : 'pl';
  const translations = {
    pl:{chooseProperty:'Wybierz nieruchomość',advisory:'Doradztwo',whyUs:'Dlaczego my',developers:'Dla deweloperów',contact:'Kontakt',contactUs:'Skontaktuj się',back:'← Wróć do wyszukiwarki',offersEyebrow:'OFERTY MAZURESTATE',sort:'Sortuj',recommended:'Polecane',newest:'Najnowsze',priceAsc:'Cena: od najniższej',priceDesc:'Cena: od najwyższej',perPage:'Pokaż na stronie',navigation:'Nawigacja',reviews:'Opinie klientów',offers:'Oferty',footerIntro:'Agencja nieruchomości w Warszawie. Sprzedaż, wynajem i kompleksowa obsługa nieruchomości.',rights:'Wszelkie prawa zastrzeżone.',types:{mieszkania:'Mieszkania',domy:'Domy',dzialki:'Działki',lokale:'Lokale komercyjne'},sale:'na sprzedaż',rent:'na wynajem',found:'Znaleziono {n} dopasowanych ofert',to:'do',from:'od',rooms:'pokoi',spaces:'pomieszczenia',plot:'Działka',utilities:'Media w drodze',floors:'2 kondygnacje',ground:'Parter',floor:'piętro',offer:'Oferta MazurEstate',prevPhoto:'Poprzednie zdjęcie',nextPhoto:'Następne zdjęcie',favorite:'Dodaj do ulubionych',prevPage:'Poprzednia strona',nextPage:'Następna strona'},
    uk:{chooseProperty:'Обрати нерухомість',advisory:'Консультації',whyUs:'Чому ми',developers:'Для забудовників',contact:'Контакти',contactUs:'Зв’язатися',back:'← Повернутися до пошуку',offersEyebrow:'ПРОПОЗИЦІЇ MAZURESTATE',sort:'Сортувати',recommended:'Рекомендовані',newest:'Найновіші',priceAsc:'Ціна: від найнижчої',priceDesc:'Ціна: від найвищої',perPage:'Показати на сторінці',navigation:'Навігація',reviews:'Відгуки клієнтів',offers:'Пропозиції',footerIntro:'Агенція нерухомості у Варшаві. Продаж, оренда та комплексний супровід нерухомості.',rights:'Усі права захищені.',types:{mieszkania:'Квартири',domy:'Будинки',dzialki:'Земельні ділянки',lokale:'Комерційні приміщення'},sale:'на продаж',rent:'в оренду',found:'Знайдено {n} відповідних пропозицій',to:'до',from:'від',rooms:'кімнат',spaces:'приміщення',plot:'Ділянка',utilities:'Комунікації поруч',floors:'2 поверхи',ground:'Перший поверх',floor:'поверх',offer:'Пропозиція MazurEstate',prevPhoto:'Попереднє фото',nextPhoto:'Наступне фото',favorite:'Додати до обраного',prevPage:'Попередня сторінка',nextPage:'Наступна сторінка'},
    en:{chooseProperty:'Choose a property',advisory:'Advisory',whyUs:'Why us',developers:'For developers',contact:'Contact',contactUs:'Contact us',back:'← Back to search',offersEyebrow:'MAZURESTATE PROPERTIES',sort:'Sort',recommended:'Recommended',newest:'Newest',priceAsc:'Price: lowest first',priceDesc:'Price: highest first',perPage:'Show per page',navigation:'Navigation',reviews:'Client reviews',offers:'Properties',footerIntro:'A Warsaw real estate agency providing sales, rentals and comprehensive property support.',rights:'All rights reserved.',types:{mieszkania:'Apartments',domy:'Houses',dzialki:'Land',lokale:'Commercial properties'},sale:'for sale',rent:'for rent',found:'{n} matching properties found',to:'up to',from:'from',rooms:'rooms',spaces:'spaces',plot:'Plot',utilities:'Utilities nearby',floors:'2 storeys',ground:'Ground floor',floor:'floor',offer:'MazurEstate property',prevPhoto:'Previous photo',nextPhoto:'Next photo',favorite:'Add to favourites',prevPage:'Previous page',nextPage:'Next page'},
    ru:{chooseProperty:'Выбрать недвижимость',advisory:'Консультации',whyUs:'Почему мы',developers:'Для застройщиков',contact:'Контакты',contactUs:'Связаться',back:'← Вернуться к поиску',offersEyebrow:'ПРЕДЛОЖЕНИЯ MAZURESTATE',sort:'Сортировать',recommended:'Рекомендуемые',newest:'Новые',priceAsc:'Цена: сначала ниже',priceDesc:'Цена: сначала выше',perPage:'Показать на странице',navigation:'Навигация',reviews:'Отзывы клиентов',offers:'Предложения',footerIntro:'Агентство недвижимости в Варшаве. Продажа, аренда и комплексное сопровождение недвижимости.',rights:'Все права защищены.',types:{mieszkania:'Квартиры',domy:'Дома',dzialki:'Участки',lokale:'Коммерческие помещения'},sale:'на продажу',rent:'в аренду',found:'Найдено {n} подходящих предложений',to:'до',from:'от',rooms:'комнат',spaces:'помещения',plot:'Участок',utilities:'Коммуникации рядом',floors:'2 этажа',ground:'Первый этаж',floor:'этаж',offer:'Предложение MazurEstate',prevPhoto:'Предыдущее фото',nextPhoto:'Следующее фото',favorite:'Добавить в избранное',prevPage:'Предыдущая страница',nextPage:'Следующая страница'}
  };
  const t=translations[lang];
  const typeLabels=t.types;
  const transactionLabel = transaction === 'wynajem' ? t.rent : t.sale;
  const images = ['../assets/images/category-apartments.webp','../assets/images/hf_20260726_144524_c09ad56f-4bf3-454e-ad5c-3ebd0166d985.png','../assets/images/category-houses.webp','../assets/images/category-commercial.webp','../assets/images/individual-approach-v2.png','../assets/images/hf_20260726_144517_90fd2149-4cca-4eef-974e-74aa570050e6.png'];
  const locations = ['Warszawa, Wilanów','Warszawa, Mokotów','Warszawa, Wola','Warszawa, Ochota','Konstancin-Jeziorna','Piaseczno','Warszawa, Żoliborz','Warszawa, Praga Południe','Ząbki','Wiązowna','Warszawa, Ursynów','Warszawa, Śródmieście'];
  const titleSets={pl:{mieszkania:['Apartament z dużym balkonem','Jasne mieszkanie blisko parku','Nowoczesne mieszkanie w spokojnej okolicy','Przestronny apartament gotowy do zamieszkania'],domy:['Nowoczesny dom dla rodziny','Dom z ogrodem blisko Warszawy','Kameralna willa w zielonej okolicy','Energooszczędny dom z garażem'],dzialki:['Działka budowlana z dobrym dojazdem','Grunt inwestycyjny w rozwijającej się okolicy','Działka z mediami przy spokojnej ulicy','Teren pod kameralną zabudowę'],lokale:['Lokal usługowy przy ruchliwej ulicy','Nowoczesne biuro w prestiżowej lokalizacji','Lokal handlowy z dużymi witrynami','Funkcjonalna przestrzeń dla Twojej firmy']},en:{mieszkania:['Apartment with a large balcony','Bright apartment near a park','Modern apartment in a quiet area','Spacious move-in-ready apartment'],domy:['Modern family house','House with a garden near Warsaw','Private villa in a green area','Energy-efficient house with a garage'],dzialki:['Building plot with good access','Investment land in a growing area','Serviced plot on a quiet street','Land for an intimate development'],lokale:['Retail unit on a busy street','Modern office in a prime location','Commercial unit with large windows','Functional space for your business']},uk:{mieszkania:['Квартира з великим балконом','Світла квартира біля парку','Сучасна квартира в тихому районі','Простора квартира, готова до заселення'],domy:['Сучасний будинок для сім’ї','Будинок із садом біля Варшави','Камерна вілла в зеленому районі','Енергоефективний будинок із гаражем'],dzialki:['Ділянка під забудову зі зручним доїздом','Інвестиційна земля в перспективному районі','Ділянка з комунікаціями на тихій вулиці','Земля під камерну забудову'],lokale:['Комерційне приміщення на жвавій вулиці','Сучасний офіс у престижній локації','Торгове приміщення з великими вітринами','Функціональний простір для Вашого бізнесу']},ru:{mieszkania:['Квартира с большим балконом','Светлая квартира рядом с парком','Современная квартира в тихом районе','Просторная квартира, готовая к заселению'],domy:['Современный дом для семьи','Дом с садом рядом с Варшавой','Уютная вилла в зелёном районе','Энергоэффективный дом с гаражом'],dzialki:['Участок под застройку с удобным подъездом','Инвестиционная земля в развивающемся районе','Участок с коммуникациями на тихой улице','Земля под камерную застройку'],lokale:['Коммерческое помещение на оживлённой улице','Современный офис в престижном месте','Торговое помещение с большими витринами','Функциональное пространство для бизнеса']}};
  const titles=titleSets[lang];
  const offers = Array.from({length:12},(_,i) => {
    const isRent = transaction === 'wynajem';
    const base = type === 'domy' ? 145 : type === 'dzialki' ? 980 : type === 'lokale' ? 92 : 48;
    const area = base + (i%6)*(type === 'dzialki' ? 170 : type === 'domy' ? 18 : 7);
    const price = isRent ? 3500 + i*420 : (type === 'domy' ? 1350000 : type === 'dzialki' ? 510000 : type === 'lokale' ? 690000 : 720000) + i*47000;
    const gallery = [images[i%images.length],images[(i+1)%images.length],images[(i+3)%images.length]];
    return {id:i+1,title:titles[type][i%4],location:locations[i],area,price,gallery,rooms:type==='dzialki'?t.plot:type==='lokale'?`${3+i%4} ${t.spaces}`:`${type==='domy'?4+i%3:2+i%4} ${t.rooms}`,floor:type==='dzialki'?t.utilities:type==='domy'?t.floors:type==='lokale'?t.ground:`${1+i%7} ${t.floor}`,date:12-i};
  });
  let currentPage=1;
  const galleryIndex={};
  const list=document.getElementById('offer-list');
  const perPage=document.getElementById('per-page');
  const pagination=document.getElementById('pagination');
  const sort=document.getElementById('sort-select');
  const money=n=>new Intl.NumberFormat(lang==='en'?'en-GB':lang==='uk'?'uk-UA':lang==='ru'?'ru-RU':'pl-PL').format(n)+' zł'+(transaction==='wynajem'?(lang==='en'?' / month':lang==='uk'?' / міс.':lang==='ru'?' / мес.':' / mies.'):'');
  const unit=o=>Math.round(o.price/o.area).toLocaleString(lang==='en'?'en-GB':'pl-PL')+' zł/m²';
  document.documentElement.lang=lang;
  document.title=`${typeLabels[type]} ${transactionLabel} | MazurEstate`;
  document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t[el.dataset.i18n]});
  document.querySelectorAll('[href^="../index.html"]').forEach(a=>{const parts=a.getAttribute('href').split('#');a.href=`../index.html?lang=${lang}${parts[1]?`#${parts[1]}`:''}`});
  document.querySelectorAll('[data-type-link]').forEach(a=>{const q=new URLSearchParams(a.search);q.set('lang',lang);a.search=q.toString();a.textContent=typeLabels[a.dataset.typeLink]});
  const langLabels={pl:'PL',uk:'UKR',en:'ENG',ru:'RU'};
  document.getElementById('language-current').textContent=langLabels[lang];
  document.querySelector(`[data-lang="${lang}"]`).classList.add('active');
  document.getElementById('results-title').textContent=`${typeLabels[type]} ${transactionLabel}${locationFilter?` — ${locationFilter}`:''}`;
  document.getElementById('results-summary').textContent=t.found.replace('{n}',offers.length);
  const chips=[typeLabels[type],transactionLabel,locationFilter,params.get('price')&&`${t.to} ${params.get('price')} PLN`,params.get('area')&&`${t.from} ${params.get('area')} m²`].filter(Boolean);
  document.getElementById('active-filters').innerHTML=chips.map(x=>`<span class="filter-chip">${x}</span>`).join('');

  function ordered(){const data=[...offers];if(sort.value==='price-asc')data.sort((a,b)=>a.price-b.price);if(sort.value==='price-desc')data.sort((a,b)=>b.price-a.price);if(sort.value==='newest')data.sort((a,b)=>a.date-b.date);return data}
  function render(){const count=Number(perPage.value);const data=ordered();const pages=Math.ceil(data.length/count);currentPage=Math.min(currentPage,pages);const visible=data.slice((currentPage-1)*count,currentPage*count);list.innerHTML=visible.map(card).join('');pagination.innerHTML=`<button class="page-button" data-page="${Math.max(1,currentPage-1)}" aria-label="${t.prevPage}">‹</button>${Array.from({length:pages},(_,i)=>`<button class="page-button ${currentPage===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}<button class="page-button" data-page="${Math.min(pages,currentPage+1)}" aria-label="${t.nextPage}">›</button>`}
  function card(o){const gi=galleryIndex[o.id]||0;return `<article class="offer-card"><div class="gallery" data-offer="${o.id}"><img src="${o.gallery[gi]}" alt="${o.title}"><button class="gallery-arrow prev" data-gallery="prev" data-id="${o.id}" aria-label="${t.prevPhoto}">‹</button><button class="gallery-arrow next" data-gallery="next" data-id="${o.id}" aria-label="${t.nextPhoto}">›</button><div class="gallery-dots">${o.gallery.map((_,i)=>`<span class="${i===gi?'active':''}"></span>`).join('')}</div><span class="gallery-count">▣ ${gi+1}/${o.gallery.length}</span></div><div class="offer-content"><div class="offer-top"><div><span class="price">${money(o.price)}</span><span class="unit-price">${unit(o)}</span></div><button class="favorite" aria-label="${t.favorite}">♡</button></div><h2>${o.title}</h2><p class="address">${o.location}, mazowieckie</p><div class="details"><span class="detail"><i class="detail-icon">⌂</i>${o.rooms}</span><span class="detail"><i class="detail-icon">↗</i>${o.area} m²</span><span class="detail"><i class="detail-icon">▦</i>${o.floor}</span></div><div class="offer-footer"><span class="offer-kind">${typeLabels[type]} ${transactionLabel}</span><span>${t.offer}</span></div></div></article>`}
  list.addEventListener('click',e=>{const arrow=e.target.closest('[data-gallery]');if(arrow){const id=Number(arrow.dataset.id),o=offers.find(x=>x.id===id),delta=arrow.dataset.gallery==='next'?1:-1;galleryIndex[id]=((galleryIndex[id]||0)+delta+o.gallery.length)%o.gallery.length;render();return}const fav=e.target.closest('.favorite');if(fav){fav.classList.toggle('active');fav.textContent=fav.classList.contains('active')?'♥':'♡';return}if(e.target.closest('.offer-card'))location.href=`../oferta/?id=4374&lang=${lang}`});
  pagination.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){currentPage=Number(b.dataset.page);render();scrollTo({top:0,behavior:'smooth'})}});
  perPage.addEventListener('change',()=>{currentPage=1;render()});sort.addEventListener('change',()=>{currentPage=1;render()});
  const picker=document.getElementById('language-picker'),trigger=picker.querySelector('.language-trigger');
  trigger.addEventListener('click',()=>{const open=picker.classList.toggle('open');trigger.setAttribute('aria-expanded',String(open))});
  picker.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{params.set('lang',button.dataset.lang);location.search=params.toString()}));
  document.addEventListener('click',e=>{if(!picker.contains(e.target)){picker.classList.remove('open');trigger.setAttribute('aria-expanded','false')}});
  render();
})();
